# Generated by Django 3.1.8 on 2021-06-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='evaluated',
        ),
    ]
