# Generated by Django 3.1.8 on 2021-06-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
