# Generated by Django 3.1.8 on 2021-06-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('evaluated', 'Evaluated'), ('on evaluation', 'On Evaluation')], default='none', max_length=255),
        ),
    ]
