# Generated by Django 3.1.8 on 2021-11-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_current_user_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(null=True),
        ),
    ]
