# Generated by Django 3.1.8 on 2021-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_hiring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiring_date',
            field=models.DateTimeField(null=True),
        ),
    ]
