# Generated by Django 3.1.8 on 2021-06-08 07:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_userevaluation_client'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='evaluationrates',
            name='evaluation_categories',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rates', to='base.evaluationcategories'),
        ),
        migrations.AddField(
            model_name='evaluationrateassign',
            name='evaluation_categories_assign',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rates_assign', to='base.evaluationcategoriesassign'),
        ),
        migrations.AddField(
            model_name='evaluationrateassign',
            name='evaluation_rates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.evaluationrates'),
        ),
        migrations.AddField(
            model_name='evaluationcategoriesassign',
            name='evaluation_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.evaluationcategories'),
        ),
        migrations.AddField(
            model_name='evaluationcategoriesassign',
            name='user_evaluation',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_categories_assign', to='base.userevaluation'),
        ),
        migrations.AddField(
            model_name='evaluationcategories',
            name='evaluation_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_categories', to='base.evaluationpage'),
        ),
    ]
