# Generated by Django 3.1.8 on 2021-06-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_assigns_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigns',
            name='client',
        ),
        migrations.RemoveField(
            model_name='assigns',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Assigns',
        ),
    ]
