# Generated by Django 3.1.8 on 2021-06-24 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_profile_pic'),
        ('base', '0003_auto_20210623_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to='employee.employee'),
        ),
    ]
