# Generated by Django 3.1.8 on 2021-06-24 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_profile_pic'),
        ('employee', '0003_employee_profile_pic'),
        ('base', '0004_auto_20210624_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to='client.client', unique=True),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to='employee.employee', unique=True),
        ),
    ]
