# Generated by Django 3.1.8 on 2021-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210605_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcategories',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
