# Generated by Django 3.1.8 on 2021-06-24 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_profile_pic'),
        ('client', '0004_client_profile_pic'),
        ('base', '0005_auto_20210624_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to='client.client'),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to='employee.employee'),
        ),
    ]
