# Generated by Django 3.1.8 on 2021-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_evaluationcategories_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrates',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
