# Generated by Django 3.1.8 on 2021-06-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_evaluationrates_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationcategories',
            old_name='rate',
            new_name='max_rate',
        ),
    ]
