# Generated by Django 3.1.8 on 2021-06-05 15:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210605_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcategories',
            name='evaluation_categories',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='base.evaluationpage'),
        ),
    ]
