# Generated by Django 3.1.8 on 2021-06-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210605_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcategories',
            name='clean_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
