# Generated by Django 3.1.8 on 2021-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210629_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
