# Generated by Django 3.1.8 on 2021-06-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_evaluationcategories_clean_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationrates',
            name='evaluation_rates',
        ),
        migrations.DeleteModel(
            name='EvaluationCategories',
        ),
        migrations.DeleteModel(
            name='EvaluationRates',
        ),
    ]
