# Generated by Django 3.1.8 on 2021-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_userevaluation_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='submit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
