# Generated by Django 3.1.8 on 2021-06-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_evaluationcategories_evaluationrates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='clean_name',
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='label',
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='required',
        ),
    ]
