# Generated by Django 3.1.8 on 2021-06-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210605_0836'),
        ('employee', '0003_auto_20210605_0219'),
        ('base', '0014_auto_20210605_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='client.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee')),
            ],
        ),
    ]
