# Generated by Django 3.1.8 on 2021-07-19 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_evaluationrateassign_hr_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationrateassign',
            name='hr_admin',
        ),
        migrations.AddField(
            model_name='userevaluation',
            name='hr_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
