# Generated by Django 3.1.8 on 2021-07-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_delete_pickclientpage'),
        ('base', '0019_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hr_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.hradmin'),
        ),
    ]
