# Generated by Django 3.1.8 on 2021-06-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_evaluationcategories_user_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='evaluation_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.evaluationcategories'),
        ),
    ]
