# Generated by Django 3.1.8 on 2021-06-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210605_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevaluation',
            old_name='evaluation_page',
            new_name='evaluation_category',
        ),
    ]
