# Generated by Django 3.1.8 on 2021-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_notification_hr_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('client-evaluated-hr', 'Client Evaluated'), ('client-evaluated-employee', 'Client Evaluated'), ('notify-evaluated-all-client', 'Notify evaluate all'), ('notify-evaluated-specific-client', 'Notify evaluate specific')], max_length=255, null=True),
        ),
    ]
