# Generated by Django 3.1.8 on 2021-07-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('client-evaluated-hr', 'Client Evaluated'), ('client-evaluated-employee', 'Client Evaluated'), ('notify-evaluated-all-client', 'Notify evaluate all'), ('notify-evaluated-specific-client', 'Notify evaluate specific'), ('new-employee-client', 'A New Employee Assigned'), ('new-client-employee', 'A New Client Assigned')], max_length=255, null=True),
        ),
    ]
