# Generated by Django 3.1.8 on 2021-07-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210722_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('client-evaluated-hr', 'Client Evaluated'), ('client-evaluated-employee', 'Client Evaluated'), ('notify-evaluated-all-client', 'Notify evaluate all'), ('notify-evaluated-specific-client', 'Notify evaluate specific'), ('new-employee-client', 'A New Employee Assigned'), ('new-client-employee', 'A New Client Assigned'), ('evaluated-form-is-send-to-employee', 'Thank You for Evaluating'), ('client-has-been-notify', 'Client has been notify')], max_length=255, null=True),
        ),
    ]
