# Generated by Django 3.1.8 on 2021-06-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210605_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationcategoriespicker',
            old_name='model',
            new_name='user_evaluation',
        ),
    ]
