# Generated by Django 3.1.8 on 2021-06-05 17:00

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210605_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='evaluation_categories_picker',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='base.EvaluationCategories', verbose_name='Choose which local newspapers categories this advert will show up to'),
        ),
        migrations.DeleteModel(
            name='EvaluationCategoriesPicker',
        ),
    ]
