# Generated by Django 3.1.8 on 2021-07-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210722_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
