# Generated by Django 3.1.8 on 2021-06-05 17:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20210605_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevaluation',
            name='evaluation_categories_picker',
        ),
        migrations.CreateModel(
            name='EvaluationCategoriesPicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('evaluation_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.evaluationcategories')),
                ('user_evaluation', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation_categories', to='base.userevaluation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
