# Generated by Django 3.1.8 on 2021-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_evaluationpage_legend_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='project_assign',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
