# Generated by Django 3.1.8 on 2021-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20210605_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationrates',
            old_name='rate_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='evaluationrates',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
