# Generated by Django 3.1.8 on 2021-06-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210605_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationrates',
            old_name='rate',
            new_name='evaluation_rate',
        ),
    ]
