# Generated by Django 3.1.8 on 2021-07-31 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20210731_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='late_and_absence',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
    ]
