# Generated by Django 3.1.8 on 2021-06-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210605_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcategories',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='evaluationrates',
            name='evaluation_rates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rates', to='base.evaluationcategories'),
        ),
    ]
