# Generated by Django 3.1.8 on 2021-06-05 17:18

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20210605_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcategories',
            options={},
        ),
        migrations.AlterField(
            model_name='evaluationrates',
            name='evaluation_rates',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rates', to='base.evaluationcategories'),
        ),
    ]
