# Generated by Django 3.1.8 on 2021-08-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0030_reportspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportsPage',
        ),
    ]
