# Generated by Django 3.1.8 on 2021-06-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20210605_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationrates',
            options={},
        ),
    ]
