# Generated by Django 3.1.8 on 2021-08-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_delete_reportspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevaluation',
            name='percentage',
        ),
    ]
