# Generated by Django 3.1.8 on 2021-06-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20210605_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
