# Generated by Django 3.1.8 on 2021-06-06 02:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_userevaluation_evaluated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRatesPicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('rate', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='evaluationrates',
            name='rate',
        ),
        migrations.DeleteModel(
            name='EvaluationCategoriesPicker',
        ),
        migrations.AddField(
            model_name='evaluationratespicker',
            name='evaluation_rates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.evaluationrates'),
        ),
        migrations.AddField(
            model_name='evaluationratespicker',
            name='user_evaluation',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation_categories', to='base.userevaluation'),
        ),
    ]
