# Generated by Django 3.1.8 on 2021-09-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_calendarorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulessettings',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='rulessettings',
            name='count',
        ),
        migrations.AddField(
            model_name='rulessettings',
            name='limit_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
