# Generated by Django 3.1.8 on 2021-06-06 03:17

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20210606_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationratespicker',
            name='user_evaluation',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation_rates', to='base.userevaluation'),
        ),
    ]
