# Generated by Django 3.1.8 on 2021-06-06 04:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20210606_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRateAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('rate', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='evaluationrates',
            old_name='evaluation_rates',
            new_name='evaluation_categories',
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='evaluation_categories',
        ),
        migrations.AddField(
            model_name='evaluationcategories',
            name='evaluation_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_page_evaluation_categories', to='base.evaluationpage'),
        ),
        migrations.AddField(
            model_name='evaluationcategories',
            name='user_evaluation',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation_evaluation_categories', to='base.userevaluation'),
        ),
        migrations.DeleteModel(
            name='EvaluationRatesPicker',
        ),
        migrations.AddField(
            model_name='evaluationrateassign',
            name='evaluation_categories',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rates_assign_evaluation_categories', to='base.evaluationcategories'),
        ),
        migrations.AddField(
            model_name='evaluationrateassign',
            name='evaluation_rates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.evaluationrates'),
        ),
    ]
