# Generated by Django 3.1.8 on 2021-09-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20210901_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulessettings',
            options={'verbose_name': 'Rules'},
        ),
    ]
