# Generated by Django 3.1.8 on 2021-06-06 04:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20210606_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='user_evaluation',
        ),
        migrations.RemoveField(
            model_name='evaluationrateassign',
            name='evaluation_categories',
        ),
        migrations.AlterField(
            model_name='evaluationcategories',
            name='evaluation_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_categories', to='base.evaluationpage'),
        ),
        migrations.CreateModel(
            name='EvaluationCategoriesAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('evaluation_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.evaluationcategories')),
                ('user_evaluation', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_categories_assign', to='base.userevaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evaluationrateassign',
            name='evaluation_categories_assign',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_rates_assign', to='base.evaluationcategoriesassign'),
        ),
    ]
