# Generated by Django 3.1.8 on 2021-09-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20210901_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
