# Generated by Django 3.1.8 on 2021-09-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_userevaluation_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevaluation',
            name='searchable_assigned_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
