# Generated by Django 3.1.8 on 2021-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20210606_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcategories',
            name='category_name',
            field=models.TextField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='evaluationrates',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Question'),
        ),
    ]
