# Generated by Django 3.1.8 on 2021-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20210606_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='max_rate',
        ),
        migrations.AddField(
            model_name='evaluationpage',
            name='evaluation_max_rate',
            field=models.IntegerField(default=0),
        ),
    ]
