# Generated by Django 3.1.8 on 2021-06-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20210606_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationrates',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='evaluationcategories',
            name='sort_order',
        ),
    ]
