# Generated by Django 3.1.8 on 2021-06-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20210605_1737'),
        ('base', '0043_auto_20210606_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to='client.client'),
        ),
    ]
