# Generated by Django 3.1.8 on 2021-10-13 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20211013_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 8, 33, 15, 938521, tzinfo=utc)),
        ),
    ]
