# Generated by Django 3.1.8 on 2021-10-26 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20211013_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 6, 37, 2, 118180, tzinfo=utc), null=True),
        ),
    ]
