# Generated by Django 3.1.8 on 2021-10-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20211026_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevaluation',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
