# Generated by Django 3.1.8 on 2021-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20211026_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulessettings',
            name='renewal_calendar',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rulessettings',
            name='renewal_count',
            field=models.IntegerField(default=0),
        ),
    ]
