# Generated by Django 3.1.8 on 2021-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20211027_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulessettings',
            name='effective_rule_calendar',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rulessettings',
            name='effective_rule_count',
            field=models.IntegerField(default=0),
        ),
    ]
