# Generated by Django 3.1.8 on 2021-05-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210503_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_initial',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
