# Generated by Django 3.1.8 on 2021-05-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210514_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
