# Generated by Django 3.1.8 on 2021-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_employee_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_initial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
