# Generated by Django 3.1.8 on 2021-05-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210514_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
