# Generated by Django 3.1.8 on 2021-05-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210515_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_no',
        ),
    ]
