# Generated by Django 3.1.8 on 2021-04-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210416_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='companies',
            new_name='company',
        ),
    ]
