# Generated by Django 3.1.8 on 2021-04-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
