# Generated by Django 3.1.8 on 2021-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
