# Generated by Django 3.1.8 on 2021-06-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210605_0219'),
        ('client', '0004_client_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='employee.employee', verbose_name='Assigned Employee'),
        ),
    ]
