# Generated by Django 3.1.8 on 2021-06-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210605_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='client',
            name='evaluated',
        ),
    ]
