# Generated by Django 3.1.8 on 2021-08-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_reportsclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
    ]
