# Generated by Django 3.1.8 on 2021-08-14 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0006_assignclient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignClient',
            new_name='AssignEmployee',
        ),
    ]
