# Generated by Django 3.1.8 on 2021-08-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('hr', '0007_auto_20210814_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientDetailsPage',
        ),
    ]
